apiVersion: apps/v1
kind: Deployment
metadata:
  name: asys-deployment-dev
  namespace: white
spec:
  selector:
    matchLabels:
      app: asys-app-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: asys-app-dev
    spec:
      containers:
        - name: asys-app-dev
          image: nrt.ocir.io/nrcbpbtrtyz0/regs-container:aip5wxb
          command: ["java"]
          args: ["-jar", "target/hello-0.0.1-SNAPSHOT.jar"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8890
              protocol: TCP
      imagePullSecrets:
        - name: asys-dev
---
apiVersion: v1
kind: Service
metadata:
  name: asys-svc-dev
  namespace: white
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8890
  selector:
    app: asys-app-dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asys-ingress-dev
  namespace: white
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "X-Powered-By";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ursa.mlhuillier.net
    secretName: net-tls
  rules:
  - host: ursa.mlhuillier.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: asys-svc-dev
            port:
              number: 80