apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-devops-deployment
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 1
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: iad.ocir.io/sehubjapaciaas/oci_devops_java_app:${BUILDRUN_HASH}
          command: ["java"]
          args: ["-jar", "target/hello-0.0.1-SNAPSHOT.jar"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8890
              protocol: TCP
          volumeMounts:
            - name: logs
              mountPath: /mnt/log
        - name: logging
          image: fluent/fluent-bit
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: logs
              mountPath: /mnt/log
            - name: fluentbit-config
              mountPath: /fluent-bit/etc
      volumes:
        - name: logs
          emptyDir: {}
        - name: fluentbit-config
          configMap:
            name: fluentbit-config-devops
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
    service.beta.kubernetes.io/oci-load-balancer-backend-protocol: "HTTP"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8890
  selector:
    app: java-app
