kind: Namespace
apiVersion: v1
metadata:
  name: ns-green
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supremo-deployment
  namespace: ns-green
spec:
  selector:
    matchLabels:
      app: python-gettingstarted
  replicas: 1
  template:
    metadata:
      labels:
        app: python-gettingstarted
    spec:
      containers:
        - name: python-gettingstarted
          # enter the path to your image, be sure to include the correct region prefix
#          image: ghcr.io/mlsysadmin/regs-devops-repo-github-action:newv1
          image: nrt.ocir.io/nrcbpbtrtyz0/regs-container:supremo-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8890
              protocol: TCP
      imagePullSecrets:
        - name: devopstest
---
apiVersion: v1
kind: Service
metadata:
  name: supremo-service
  namespace: ns-green
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8890
  selector:
    app: python-gettingstarted