apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-oke-bg-app-deployment
  namespace: ns-green
spec:
  selector:
    matchLabels:
      app: sample-oke-bg-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-oke-bg-app
    spec:
      containers:
        - name: sample-oke-bg-app
          # enter the path to your image, be sure to include the correct region prefix
          image: nrt.ocir.io/nrcbpbtrtyz0/regs-container:qlkphkg
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - cat
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
      - name: nsgreen-secret                  
---
apiVersion: v1
kind: Service
metadata:
  name: sample-oke-bg-app-service
  namespace: ns-green
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: sample-oke-bg-app